#!/usr/bin/env bash
# setup and run nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
