#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" in the 9th position
i=1
while [ $i -lt 11 ]
do
echo "Holberton School"
if [ $i == 9 ]
then
echo "Hi"
fi
i=$((i+1))
done