#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20, "bad luck" and "good luck" in certain position
i=1
while [ $i -lt 21 ]
do
	case $i in

		4)
			echo " $i "
			echo " bad luck from China "
			;;
		9)
			echo " $i "
			echo " bad luck from Japan "
			;;
		17)
			echo " $i "
			echo " bad luck from Italy "
			;;
		* )
			echo " $i "
			;;
	esac

	i=$((i+1))
done
